name: "Build Pull Request"
on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.3.0
            - uses: actions/setup-java@v3.10.0
              with:
                  distribution: temurin
                  java-version: 17

            - name: Prepare cached external dependencies
              uses: actions/cache@v3
              with:
                  key: readyougestalt_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
                  path: |
                      external
            - name: Download build dependencies
              uses: ./.github/actions/download-externals-action

            - uses: gradle/gradle-build-action@v2.4.2
            - run: gradle testGestaltReleaseUnitTest

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.3.0
            - uses: actions/setup-java@v3.10.0
              with:
                  distribution: temurin
                  java-version: 17

            - name: Prepare cached external dependencies
              uses: actions/cache@v3
              with:
                  key: readyougestalt_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
                  path: |
                      external
            - name: Download build dependencies
              uses: ./.github/actions/download-externals-action

            - uses: gradle/gradle-build-action@v2.4.2
            - run: gradle assembleRelease

            - uses: actions/upload-artifact@v3.1.1
              with:
                  name: gestalt-${{ github.sha }}
                  path: app/build/outputs/apk/gestalt/release/*.apk
